# ------------------------------
# GitHub Pages Configuration
# ------------------------------

# Site settings
title: "Grantha Saha – Data Science Portfolio"
description: "Grantha Saha's personal portfolio showcasing Data Science projects, skills, certificates, and contact information."
url: "https://gsgrantha.github.io" # Replace with your GitHub username if different
baseurl: "" # Leave empty if deployed at root
language: "en"

# Author info
author:
  name: "Grantha Saha"
  email: "granthasaha.dse@gmail.com"
  github: "gsgrantha"
  location: "Dhaka, Bangladesh"

# Sections (to reflect your HTML nav & content)
sections:
  - hero
  - about
  - profile
  - education
  - experience
  - skills
  - projects
  - certificates
  - contact

# Social links for footer or SEO
social_links:
  github: "https://github.com/gsgrantha"
  linkedin: "https://www.linkedin.com/in/granthasaha/"
  email: "mailto:granthasaha.dse@gmail.com"
  phone: "tel:01800090078"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# GitHub Pages
github:
  is_project_page: true

# Optional plugins (for SEO or feed if needed)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude unnecessary files from the build
exclude:
  - README.md
  - node_modules
  - vendor

# Theme (optional; your site uses custom HTML/CSS)
theme: minima
